export const ABOUT_CREATE_REQUEST = 'ABOUT_CREATE_REQUEST';
export const ABOUT_CREATE_SUCCESS = 'ABOUT_CREATE_SUCCESS';
export const ABOUT_CREATE_FAIL = 'ABOUT_CREATE_FAIL';

export const ABOUT_LIST_REQUEST = 'ABOUT_LIST_REQUEST';
export const ABOUT_LIST_SUCCESS = 'ABOUT_LIST_SUCCESS';
export const ABOUT_LIST_FAIL = 'ABOUT_LIST_FAIL';

export const ABOUT_EMPLOYEE_LIST_REQUEST = 'ABOUT_EMPLOYEE_LIST_REQUEST';
export const ABOUT_EMPLOYEE_LIST_SUCCESS = 'ABOUT_EMPLOYEE_LIST_SUCCESS';
export const ABOUT_EMPLOYEE_LIST_FAIL = 'ABOUT_EMPLOYEE_LIST_FAIL';

export const ABOUT_EDIT_REQUEST = 'ABOUT_EDIT_REQUEST';
export const ABOUT_EDIT_SUCCESS = 'ABOUT_EDIT_SUCCESS';
export const ABOUT_EDIT_FAIL = 'ABOUT_EDIT_FAIL';

export const ABOUT_MANAGEMENT_CONTENT_ADD_REQUEST = 'ABOUT_MANAGEMENT_CONTENT_ADD_REQUEST';
export const ABOUT_MANAGEMENT_CONTENT_ADD_SUCCESS = 'ABOUT_MANAGEMENT_CONTENT_ADD_SUCCESS';
export const ABOUT_MANAGEMENT_CONTENT_ADD_FAIL = 'ABOUT_MANAGEMENT_CONTENT_ADD_FAIL';

export const ABOUT_MANAGEMENT_CONTENT_EDIT_REQUEST = 'ABOUT_MANAGEMENT_CONTENT_EDIT_REQUEST';
export const ABOUT_MANAGEMENT_CONTENT_EDIT_SUCCESS = 'ABOUT_MANAGEMENT_CONTENT_EDIT_SUCCESS';
export const ABOUT_MANAGEMENT_CONTENT_EDIT_FAIL = 'ABOUT_MANAGEMENT_CONTENT_EDIT_FAIL';

export const ABOUT_MANAGEMENT_CONTENT_DELETE_REQUEST = 'ABOUT_MANAGEMENT_CONTENT_DELETE_REQUEST';
export const ABOUT_MANAGEMENT_CONTENT_DELETE_SUCCESS = 'ABOUT_MANAGEMENT_CONTENT_DELETE_SUCCESS';
export const ABOUT_MANAGEMENT_CONTENT_DELETE_FAIL = 'ABOUT_MANAGEMENT_CONTENT_DELETE_FAIL';