export const USER_ADDRESS_SAVE_REQUEST = 'USER_ADDRESS_SAVE_REQUEST';
export const USER_ADDRESS_SAVE_SUCCESS = 'USER_ADDRESS_SAVE_SUCCESS';
export const USER_ADDRESS_SAVE_FAIL = 'USER_ADDRESS_SAVE_FAIL';

export const USER_ADDRESS_EDIT_REQUEST = 'USER_ADDRESS_EDIT_REQUEST';
export const USER_ADDRESS_EDIT_SUCCESS = 'USER_ADDRESS_EDIT_SUCCESS';
export const USER_ADDRESS_EDIT_FAIL = 'USER_ADDRESS_EDIT_FAIL';

export const USER_ADDRESS_DELETE_REQUEST = 'USER_ADDRESS_DELETE_REQUEST';
export const USER_ADDRESS_DELETE_SUCCESS = 'USER_ADDRESS_DELETE_SUCCESS';
export const USER_ADDRESS_DELETE_FAIL = 'USER_ADDRESS_DELETE_FAIL';

export const USER_ADDRESS_LIST_REQUEST = 'USER_ADDRESS_LIST_REQUEST';
export const USER_ADDRESS_LIST_SUCCESS = 'USER_ADDRESS_LIST_SUCCESS';
export const USER_ADDRESS_LIST_FAIL = 'USER_ADDRESS_LIST_FAIL';