export const BLOG_CREATE_REQUEST = 'BLOG_CREATE_REQUEST';
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS';
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL';

export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST';
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS';
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL';

export const BLOG_EDIT_REQUEST = 'BLOG_EDIT_REQUEST';
export const BLOG_EDIT_SUCCESS = 'BLOG_EDIT_SUCCESS';
export const BLOG_EDIT_FAIL = 'BLOG_EDIT_FAIL';

export const BLOG_CONTENT_ADD_REQUEST = 'BLOG_CONTENT_ADD_REQUEST';
export const BLOG_CONTENT_ADD_SUCCESS = 'BLOG_CONTENT_ADD_SUCCESS';
export const BLOG_CONTENT_ADD_FAIL = 'BLOG_CONTENT_ADD_FAIL';

export const BLOG_CONTENT_EDIT_REQUEST = 'BLOG_CONTENT_EDIT_REQUEST';
export const BLOG_CONTENT_EDIT_SUCCESS = 'BLOG_CONTENT_EDIT_SUCCESS';
export const BLOG_CONTENT_EDIT_FAIL = 'BLOG_CONTENT_EDIT_FAIL';

export const BLOG_CONTENT_DELETE_REQUEST = 'BLOG_CONTENT_DELETE_REQUEST';
export const BLOG_CONTENT_DELETE_SUCCESS = 'BLOG_CONTENT_DELETE_SUCCESS';
export const BLOG_CONTENT_DELETE_FAIL = 'BLOG_CONTENT_DELETE_FAIL';