export const CAREERS_CREATE_REQUEST = 'CAREERS_CREATE_REQUEST';
export const CAREERS_CREATE_SUCCESS = 'CAREERS_CREATE_SUCCESS';
export const CAREERS_CREATE_FAIL = 'CAREERS_CREATE_FAIL';

export const CAREERS_LIST_REQUEST = 'CAREERS_LIST_REQUEST';
export const CAREERS_LIST_SUCCESS = 'CAREERS_LIST_SUCCESS';
export const CAREERS_LIST_FAIL = 'CAREERS_LIST_FAIL';

export const CAREERS_EMPLOYEE_LIST_REQUEST = 'CAREERS_EMPLOYEE_LIST_REQUEST';
export const CAREERS_EMPLOYEE_LIST_SUCCESS = 'CAREERS_EMPLOYEE_LIST_SUCCESS';
export const CAREERS_EMPLOYEE_LIST_FAIL = 'CAREERS_EMPLOYEE_LIST_FAIL';

export const CAREERS_EDIT_REQUEST = 'CAREERS_EDIT_REQUEST';
export const CAREERS_EDIT_SUCCESS = 'CAREERS_EDIT_SUCCESS';
export const CAREERS_EDIT_FAIL = 'CAREERS_EDIT_FAIL';

export const CAREERS_JOB_OPENINGS_CONTENT_ADD_REQUEST = 'CAREERS_JOB_OPENINGS_CONTENT_ADD_REQUEST';
export const CAREERS_JOB_OPENINGS_CONTENT_ADD_SUCCESS = 'CAREERS_JOB_OPENINGS_CONTENT_ADD_SUCCESS';
export const CAREERS_JOB_OPENINGS_CONTENT_ADD_FAIL = 'CAREERS_JOB_OPENINGS_CONTENT_ADD_FAIL';

export const CAREERS_JOB_OPENINGS_CONTENT_EDIT_REQUEST = 'CAREERS_JOB_OPENINGS_CONTENT_EDIT_REQUEST';
export const CAREERS_JOB_OPENINGS_CONTENT_EDIT_SUCCESS = 'CAREERS_JOB_OPENINGS_CONTENT_EDIT_SUCCESS';
export const CAREERS_JOB_OPENINGS_CONTENT_EDIT_FAIL = 'CAREERS_JOB_OPENINGS_CONTENT_EDIT_FAIL';

export const CAREERS_JOB_OPENINGS_CONTENT_DELETE_REQUEST = 'CAREERS_JOB_OPENINGS_CONTENT_DELETE_REQUEST';
export const CAREERS_JOB_OPENINGS_CONTENT_DELETE_SUCCESS = 'CAREERS_JOB_OPENINGS_CONTENT_DELETE_SUCCESS';
export const CAREERS_JOB_OPENINGS_CONTENT_DELETE_FAIL = 'CAREERS_JOB_OPENINGS_CONTENT_DELETE_FAIL';

export const CAREERS_ARTICLES_CONTENT_ADD_REQUEST = 'CAREERS_ARTICLES_CONTENT_ADD_REQUEST';
export const CAREERS_ARTICLES_CONTENT_ADD_SUCCESS = 'CAREERS_ARTICLES_CONTENT_ADD_SUCCESS';
export const CAREERS_ARTICLES_CONTENT_ADD_FAIL = 'CAREERS_ARTICLES_CONTENT_ADD_FAIL';

export const CAREERS_ARTICLES_CONTENT_EDIT_REQUEST = 'CAREERS_ARTICLES_CONTENT_EDIT_REQUEST';
export const CAREERS_ARTICLES_CONTENT_EDIT_SUCCESS = 'CAREERS_ARTICLES_CONTENT_EDIT_SUCCESS';
export const CAREERS_ARTICLES_CONTENT_EDIT_FAIL = 'CAREERS_ARTICLES_CONTENT_EDIT_FAIL';

export const CAREERS_ARTICLES_CONTENT_DELETE_REQUEST = 'CAREERS_ARTICLES_CONTENT_DELETE_REQUEST';
export const CAREERS_ARTICLES_CONTENT_DELETE_SUCCESS = 'CAREERS_ARTICLES_CONTENT_DELETE_SUCCESS';
export const CAREERS_ARTICLES_CONTENT_DELETE_FAIL = 'CAREERS_ARTICLES_CONTENT_DELETE_FAIL';