export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_LIST_ITEM = 'CART_LIST_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_EMPTY = 'CART_EMPTY';

export const BUY_NOW_ADD_ITEM = 'BUY_NOW_ADD_ITEM';
export const BUY_NOW_REMOVE_ITEM = 'BUY_NOW_REMOVE_ITEM';
export const BUY_NOW_EMPTY = 'BUY_NOW_EMPTY';