export const EMPLOYEE_SIGNIN_REQUEST = 'EMPLOYEE_SIGNIN_REQUEST';
export const EMPLOYEE_SIGNIN_SUCCESS = 'EMPLOYEE_SIGNIN_SUCCESS';
export const EMPLOYEE_SIGNIN_FAIL = 'EMPLOYEE_SIGNIN_FAIL';

export const EMPLOYEE_REGISTER_REQUEST = 'EMPLOYEE_REGISTER_REQUEST';
export const EMPLOYEE_REGISTER_SUCCESS = 'EMPLOYEE_REGISTER_SUCCESS';
export const EMPLOYEE_REGISTER_FAIL = 'EMPLOYEE_REGISTER_FAIL';

export const CALL_CENTER_GUYS_LIST_REQUEST = 'CALL_CENTER_GUYS_LIST_REQUEST';
export const CALL_CENTER_GUYS_LIST_SUCCESS = 'CALL_CENTER_GUYS_LIST_SUCCESS';
export const CALL_CENTER_GUYS_LIST_FAIL = 'CALL_CENTER_GUYS_LIST_FAIL';

export const DELIVERY_GUYS_LIST_REQUEST = 'DELIVERY_GUYS_LIST_REQUEST';
export const DELIVERY_GUYS_LIST_SUCCESS = 'DELIVERY_GUYS_LIST_SUCCESS';
export const DELIVERY_GUYS_LIST_FAIL = 'DELIVERY_GUYS_LIST_FAIL';