export const EXPORTS_CREATE_REQUEST = 'EXPORTS_CREATE_REQUEST';
export const EXPORTS_CREATE_SUCCESS = 'EXPORTS_CREATE_SUCCESS';
export const EXPORTS_CREATE_FAIL = 'EXPORTS_CREATE_FAIL';

export const EXPORTS_LIST_REQUEST = 'EXPORTS_LIST_REQUEST';
export const EXPORTS_LIST_SUCCESS = 'EXPORTS_LIST_SUCCESS';
export const EXPORTS_LIST_FAIL = 'EXPORTS_LIST_FAIL';

export const EXPORTS_EDIT_REQUEST = 'EXPORTS_EDIT_REQUEST';
export const EXPORTS_EDIT_SUCCESS = 'EXPORTS_EDIT_SUCCESS';
export const EXPORTS_EDIT_FAIL = 'EXPORTS_EDIT_FAIL';

export const EXPORTS_CONTENT_ADD_REQUEST = 'EXPORTS_CONTENT_ADD_REQUEST';
export const EXPORTS_CONTENT_ADD_SUCCESS = 'EXPORTS_CONTENT_ADD_SUCCESS';
export const EXPORTS_CONTENT_ADD_FAIL = 'EXPORTS_CONTENT_ADD_FAIL';

export const EXPORTS_CONTENT_EDIT_REQUEST = 'EXPORTS_CONTENT_EDIT_REQUEST';
export const EXPORTS_CONTENT_EDIT_SUCCESS = 'EXPORTS_CONTENT_EDIT_SUCCESS';
export const EXPORTS_CONTENT_EDIT_FAIL = 'EXPORTS_CONTENT_EDIT_FAIL';

export const EXPORTS_CONTENT_DELETE_REQUEST = 'EXPORTS_CONTENT_DELETE_REQUEST';
export const EXPORTS_CONTENT_DELETE_SUCCESS = 'EXPORTS_CONTENT_DELETE_SUCCESS';
export const EXPORTS_CONTENT_DELETE_FAIL = 'EXPORTS_CONTENT_DELETE_FAIL';