export const HELP_CREATE_REQUEST = 'HELP_CREATE_REQUEST';
export const HELP_CREATE_SUCCESS = 'HELP_CREATE_SUCCESS';
export const HELP_CREATE_FAIL = 'HELP_CREATE_FAIL';

export const HELP_LIST_REQUEST = 'HELP_LIST_REQUEST';
export const HELP_LIST_SUCCESS = 'HELP_LIST_SUCCESS';
export const HELP_LIST_FAIL = 'HELP_LIST_FAIL';

export const HELP_EMPLOYEE_LIST_REQUEST = 'HELP_EMPLOYEE_LIST_REQUEST';
export const HELP_EMPLOYEE_LIST_SUCCESS = 'HELP_EMPLOYEE_LIST_SUCCESS';
export const HELP_EMPLOYEE_LIST_FAIL = 'HELP_EMPLOYEE_LIST_FAIL';

export const HELP_EDIT_REQUEST = 'HELP_EDIT_REQUEST';
export const HELP_EDIT_SUCCESS = 'HELP_EDIT_SUCCESS';
export const HELP_EDIT_FAIL = 'HELP_EDIT_FAIL';

export const HELP_DELETE_REQUEST = 'HELP_DELETE_REQUEST';
export const HELP_DELETE_SUCCESS = 'HELP_DELETE_SUCCESS';
export const HELP_DELETE_FAIL = 'HELP_DELETE_FAIL';