export const HOMESCREEN_CREATE_REQUEST = 'HOMESCREEN_CREATE_REQUEST';
export const HOMESCREEN_CREATE_SUCCESS = 'HOMESCREEN_CREATE_SUCCESS';
export const HOMESCREEN_CREATE_FAIL = 'HOMESCREEN_CREATE_FAIL';

export const HOMESCREEN_LIST_REQUEST = 'HOMESCREEN_LIST_REQUEST';
export const HOMESCREEN_LIST_SUCCESS = 'HOMESCREEN_LIST_SUCCESS';
export const HOMESCREEN_LIST_FAIL = 'HOMESCREEN_LIST_FAIL';

export const HOMESCREEN_EDIT_REQUEST = 'HOMESCREEN_EDIT_REQUEST';
export const HOMESCREEN_EDIT_SUCCESS = 'HOMESCREEN_EDIT_SUCCESS';
export const HOMESCREEN_EDIT_FAIL = 'HOMESCREEN_EDIT_FAIL';