export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL';
export const SHOW_FORGET_PASSWORD_MODAL = 'SHOW_FORGET_PASSWORD_MODAL';

export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const HIDE_REGISTER_MODAL = 'HIDE_REGISTER_MODAL';
export const HIDE_FORGET_PASSWORD_MODAL = 'HIDE_FORGET_PASSWORD_MODAL';

export const HIDE_ALL_MODAL = 'HIDE_ALL_MODAL';
