export const LOGO_CREATE_REQUEST = 'LOGO_CREATE_REQUEST';
export const LOGO_CREATE_SUCCESS = 'LOGO_CREATE_SUCCESS';
export const LOGO_CREATE_FAIL = 'LOGO_CREATE_FAIL';

export const LOGO_LIST_REQUEST = 'LOGO_LIST_REQUEST';
export const LOGO_LIST_SUCCESS = 'LOGO_LIST_SUCCESS';
export const LOGO_LIST_FAIL = 'LOGO_LIST_FAIL';

export const LOGO_EDIT_REQUEST = 'LOGO_EDIT_REQUEST';
export const LOGO_EDIT_SUCCESS = 'LOGO_EDIT_SUCCESS';
export const LOGO_EDIT_FAIL = 'LOGO_EDIT_FAIL';