export const ORDER_DIVISION_CREATE_REQUEST = 'ORDER_DIVISION_CREATE_REQUEST';
export const ORDER_DIVISION_CREATE_SUCCESS = 'ORDER_DIVISION_CREATE_SUCCESS';
export const ORDER_DIVISION_CREATE_FAIL = 'ORDER_DIVISION_CREATE_FAIL';

export const ORDER_DIVISION_LIST_REQUEST = 'ORDER_DIVISION_LIST_REQUEST';
export const ORDER_DIVISION_LIST_SUCCESS = 'ORDER_DIVISION_LIST_SUCCESS';
export const ORDER_DIVISION_LIST_FAIL = 'ORDER_DIVISION_LIST_FAIL';

export const ORDER_ZONES_LIST_REQUEST = 'ORDER_ZONES_LIST_REQUEST';
export const ORDER_ZONES_LIST_SUCCESS = 'ORDER_ZONES_LIST_SUCCESS';
export const ORDER_ZONES_LIST_FAIL = 'ORDER_ZONES_LIST_FAIL';

export const ORDER_DIVISION_EDIT_REQUEST = 'ORDER_DIVISION_EDIT_REQUEST';
export const ORDER_DIVISION_EDIT_SUCCESS = 'ORDER_DIVISION_EDIT_SUCCESS';
export const ORDER_DIVISION_EDIT_FAIL = 'ORDER_DIVISION_EDIT_FAIL';

export const ORDER_DIVISION_DELETE_REQUEST = 'ORDER_DIVISION_DELETE_REQUEST';
export const ORDER_DIVISION_DELETE_SUCCESS = 'ORDER_DIVISION_DELETE_SUCCESS';
export const ORDER_DIVISION_DELETE_FAIL = 'ORDER_DIVISION_DELETE_FAIL';