export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST';
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS';
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';

export const ORDER_EMPLOYEE_CANCEL_REQUEST = 'ORDER_EMPLOYEE_CANCEL_REQUEST';
export const ORDER_EMPLOYEE_CANCEL_SUCCESS = 'ORDER_EMPLOYEE_CANCEL_SUCCESS';
export const ORDER_EMPLOYEE_CANCEL_FAIL = 'ORDER_EMPLOYEE_CANCEL_FAIL';

export const ORDER_CALL_CENTER_LIST_REQUEST = 'ORDER_CALL_CENTER_LIST_REQUEST';
export const ORDER_CALL_CENTER_LIST_SUCCESS = 'ORDER_CALL_CENTER_LIST_SUCCESS';
export const ORDER_CALL_CENTER_LIST_FAIL = 'ORDER_CALL_CENTER_LIST_FAIL';

export const ORDER_REASSIGN_LIST_REQUEST = 'ORDER_REASSIGN_LIST_REQUEST';
export const ORDER_REASSIGN_LIST_SUCCESS = 'ORDER_REASSIGN_LIST_SUCCESS';
export const ORDER_REASSIGN_LIST_FAIL = 'ORDER_REASSIGN_LIST_FAIL';

export const ORDER_CALL_CENTER_BOSS_LIST_REQUEST = 'ORDER_CALL_CENTER_BOSS_LIST_REQUEST';
export const ORDER_CALL_CENTER_BOSS_LIST_SUCCESS = 'ORDER_CALL_CENTER_BOSS_LIST_SUCCESS';
export const ORDER_CALL_CENTER_BOSS_LIST_FAIL = 'ORDER_CALL_CENTER_BOSS_LIST_FAIL';

export const ORDER_DELIVERY_LIST_REQUEST = 'ORDER_DELIVERY_LIST_REQUEST';
export const ORDER_DELIVERY_LIST_SUCCESS = 'ORDER_DELIVERY_LIST_SUCCESS';
export const ORDER_DELIVERY_LIST_FAIL = 'ORDER_DELIVERY_LIST_FAIL';

export const ORDER_SUPPLY_CHAIN_LIST_REQUEST = 'ORDER_SUPPLY_CHAIN_LIST_REQUEST';
export const ORDER_SUPPLY_CHAIN_LIST_SUCCESS = 'ORDER_SUPPLY_CHAIN_LIST_SUCCESS';
export const ORDER_SUPPLY_CHAIN_LIST_FAIL = 'ORDER_SUPPLY_CHAIN_LIST_FAIL';

export const ORDER_FEEDBACK_LIST_REQUEST = 'ORDER_FEEDBACK_LIST_REQUEST';
export const ORDER_FEEDBACK_LIST_SUCCESS = 'ORDER_FEEDBACK_LIST_SUCCESS';
export const ORDER_FEEDBACK_LIST_FAIL = 'ORDER_FEEDBACK_LIST_FAIL';

export const ORDER_CALL_CENTER_ASSIGN_REQUEST = 'ORDER_CALL_CENTER_ASSIGN_REQUEST';
export const ORDER_CALL_CENTER_ASSIGN_SUCCESS = 'ORDER_CALL_CENTER_ASSIGN_SUCCESS';
export const ORDER_CALL_CENTER_ASSIGN_FAIL = 'ORDER_CALL_CENTER_ASSIGN_FAIL';

export const ORDER_DELIVERY_GUY_ASSIGN_REQUEST = 'ORDER_DELIVERY_GUY_ASSIGN_REQUEST';
export const ORDER_DELIVERY_GUY_ASSIGN_SUCCESS = 'ORDER_DELIVERY_GUY_ASSIGN_SUCCESS';
export const ORDER_DELIVERY_GUY_ASSIGN_FAIL = 'ORDER_DELIVERY_GUY_ASSIGN_FAIL';

export const ORDER_FEEDBACK_ASSIGN_REQUEST = 'ORDER_FEEDBACK_ASSIGN_REQUEST';
export const ORDER_FEEDBACK_ASSIGN_SUCCESS = 'ORDER_FEEDBACK_ASSIGN_SUCCESS';
export const ORDER_FEEDBACK_ASSIGN_FAIL = 'ORDER_FEEDBACK_ASSIGN_FAIL';

export const ORDER_TAKE_FEEDBACK_REQUEST = 'ORDER_TAKE_FEEDBACK_REQUEST';
export const ORDER_TAKE_FEEDBACK_SUCCESS = 'ORDER_TAKE_FEEDBACK_SUCCESS';
export const ORDER_TAKE_FEEDBACK_FAIL = 'ORDER_TAKE_FEEDBACK_FAIL';

export const ORDER_AUTHORIZE_REQUEST = 'ORDER_AUTHORIZE_REQUEST';
export const ORDER_AUTHORIZE_SUCCESS = 'ORDER_AUTHORIZE_SUCCESS';
export const ORDER_AUTHORIZE_FAIL = 'ORDER_AUTHORIZE_FAIL';

export const ORDER_PICKUP_REQUEST = 'ORDER_PICKUP_REQUEST';
export const ORDER_PICKUP_SUCCESS = 'ORDER_PICKUP_SUCCESS';
export const ORDER_PICKUP_FAIL = 'ORDER_PICKUP_FAIL';

export const ORDER_PROCESS_REQUEST = 'ORDER_PROCESS_REQUEST';
export const ORDER_PROCESS_SUCCESS = 'ORDER_PROCESS_SUCCESS';
export const ORDER_PROCESS_FAIL = 'ORDER_PROCESS_FAIL';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';

export const ORDER_COMPLETE_REQUEST = 'ORDER_COMPLETE_REQUEST';
export const ORDER_COMPLETE_SUCCESS = 'ORDER_COMPLETE_SUCCESS';
export const ORDER_COMPLETE_FAIL = 'ORDER_COMPLETE_FAIL';

export const ORDER_ITEMS_EDIT_REQUEST = 'ORDER_ITEMS_EDIT_REQUEST';
export const ORDER_ITEMS_EDIT_SUCCESS = 'ORDER_ITEMS_EDIT_SUCCESS';
export const ORDER_ITEMS_EDIT_FAIL = 'ORDER_ITEMS_EDIT_FAIL';

export const ORDER_SPLIT_ITEMS_EDIT_REQUEST = 'ORDER_SPLIT_ITEMS_EDIT_REQUEST';
export const ORDER_SPLIT_ITEMS_EDIT_SUCCESS = 'ORDER_SPLIT_ITEMS_EDIT_SUCCESS';
export const ORDER_SPLIT_ITEMS_EDIT_FAIL = 'ORDER_SPLIT_ITEMS_EDIT_FAIL';

export const ORDER_EDIT_REQUEST = 'ORDER_EDIT_REQUEST';
export const ORDER_EDIT_SUCCESS = 'ORDER_EDIT_SUCCESS';
export const ORDER_EDIT_FAIL = 'ORDER_EDIT_FAIL';

export const ORDER_PRICE_EDIT_REQUEST = 'ORDER_PRICE_EDIT_REQUEST';
export const ORDER_PRICE_EDIT_SUCCESS = 'ORDER_PRICE_EDIT_SUCCESS';
export const ORDER_PRICE_EDIT_FAIL = 'ORDER_PRICE_EDIT_FAIL';

export const ORDER_PARTIAL_CREATE_REQUEST = 'ORDER_PARTIAL_CREATE_REQUEST';
export const ORDER_PARTIAL_CREATE_SUCCESS = 'ORDER_PARTIAL_CREATE_SUCCESS';
export const ORDER_PARTIAL_CREATE_FAIL = 'ORDER_PARTIAL_CREATE_FAIL';