export const PARTNER_CREATE_REQUEST = 'PARTNER_CREATE_REQUEST';
export const PARTNER_CREATE_SUCCESS = 'PARTNER_CREATE_SUCCESS';
export const PARTNER_CREATE_FAIL = 'PARTNER_CREATE_FAIL';

export const PARTNER_LIST_REQUEST = 'PARTNER_LIST_REQUEST';
export const PARTNER_LIST_SUCCESS = 'PARTNER_LIST_SUCCESS';
export const PARTNER_LIST_FAIL = 'PARTNER_LIST_FAIL';

export const PARTNER_EDIT_REQUEST = 'PARTNER_EDIT_REQUEST';
export const PARTNER_EDIT_SUCCESS = 'PARTNER_EDIT_SUCCESS';
export const PARTNER_EDIT_FAIL = 'PARTNER_EDIT_FAIL';

export const PARTNER_CONTENT_ADD_REQUEST = 'PARTNER_CONTENT_ADD_REQUEST';
export const PARTNER_CONTENT_ADD_SUCCESS = 'PARTNER_CONTENT_ADD_SUCCESS';
export const PARTNER_CONTENT_ADD_FAIL = 'PARTNER_CONTENT_ADD_FAIL';

export const PARTNER_CONTENT_EDIT_REQUEST = 'PARTNER_CONTENT_EDIT_REQUEST';
export const PARTNER_CONTENT_EDIT_SUCCESS = 'PARTNER_CONTENT_EDIT_SUCCESS';
export const PARTNER_CONTENT_EDIT_FAIL = 'PARTNER_CONTENT_EDIT_FAIL';

export const PARTNER_CONTENT_DELETE_REQUEST = 'PARTNER_CONTENT_DELETE_REQUEST';
export const PARTNER_CONTENT_DELETE_SUCCESS = 'PARTNER_CONTENT_DELETE_SUCCESS';
export const PARTNER_CONTENT_DELETE_FAIL = 'PARTNER_CONTENT_DELETE_FAIL';