export const PRICE_CREATE_REQUEST = 'PRICE_CREATE_REQUEST';
export const PRICE_CREATE_SUCCESS = 'PRICE_CREATE_SUCCESS';
export const PRICE_CREATE_FAIL = 'PRICE_CREATE_FAIL';

export const PRICE_LIST_REQUEST = 'PRICE_LIST_REQUEST';
export const PRICE_LIST_SUCCESS = 'PRICE_LIST_SUCCESS';
export const PRICE_LIST_FAIL = 'PRICE_LIST_FAIL';

export const PRICE_EDIT_REQUEST = 'PRICE_EDIT_REQUEST';
export const PRICE_EDIT_SUCCESS = 'PRICE_EDIT_SUCCESS';
export const PRICE_EDIT_FAIL = 'PRICE_EDIT_FAIL';

export const PRICE_DELIVERY_CHARGES_ADD_REQUEST = 'PRICE_DELIVERY_CHARGES_ADD_REQUEST';
export const PRICE_DELIVERY_CHARGES_ADD_SUCCESS = 'PRICE_DELIVERY_CHARGES_ADD_SUCCESS';
export const PRICE_DELIVERY_CHARGES_ADD_FAIL = 'PRICE_DELIVERY_CHARGES_ADD_FAIL';

export const PRICE_DELIVERY_CHARGES_EDIT_REQUEST = 'PRICE_DELIVERY_CHARGES_EDIT_REQUEST';
export const PRICE_DELIVERY_CHARGES_EDIT_SUCCESS = 'PRICE_DELIVERY_CHARGES_EDIT_SUCCESS';
export const PRICE_DELIVERY_CHARGES_EDIT_FAIL = 'PRICE_DELIVERY_CHARGES_EDIT_FAIL';

export const PRICE_DELIVERY_CHARGES_DELETE_REQUEST = 'PRICE_DELIVERY_CHARGES_DELETE_REQUEST';
export const PRICE_DELIVERY_CHARGES_DELETE_SUCCESS = 'PRICE_DELIVERY_CHARGES_DELETE_SUCCESS';
export const PRICE_DELIVERY_CHARGES_DELETE_FAIL = 'PRICE_DELIVERY_CHARGES_DELETE_FAIL';

export const PRICE_PRODUCT_DISCOUNT_ADD_REQUEST = 'PRICE_PRODUCT_DISCOUNT_ADD_REQUEST';
export const PRICE_PRODUCT_DISCOUNT_ADD_SUCCESS = 'PRICE_PRODUCT_DISCOUNT_ADD_SUCCESS';
export const PRICE_PRODUCT_DISCOUNT_ADD_FAIL = 'PRICE_PRODUCT_DISCOUNT_ADD_FAIL';

export const PRICE_PRODUCT_DISCOUNT_EDIT_REQUEST = 'PRICE_PRODUCT_DISCOUNT_EDIT_REQUEST';
export const PRICE_PRODUCT_DISCOUNT_EDIT_SUCCESS = 'PRICE_PRODUCT_DISCOUNT_EDIT_SUCCESS';
export const PRICE_PRODUCT_DISCOUNT_EDIT_FAIL = 'PRICE_PRODUCT_DISCOUNT_EDIT_FAIL';

export const PRICE_PRODUCT_DISCOUNT_DELETE_REQUEST = 'PRICE_PRODUCT_DISCOUNT_DELETE_REQUEST';
export const PRICE_PRODUCT_DISCOUNT_DELETE_SUCCESS = 'PRICE_PRODUCT_DISCOUNT_DELETE_SUCCESS';
export const PRICE_PRODUCT_DISCOUNT_DELETE_FAIL = 'PRICE_PRODUCT_DISCOUNT_DELETE_FAIL';

export const PRICE_USER_DISCOUNT_ADD_REQUEST = 'PRICE_USER_DISCOUNT_ADD_REQUEST';
export const PRICE_USER_DISCOUNT_ADD_SUCCESS = 'PRICE_USER_DISCOUNT_ADD_SUCCESS';
export const PRICE_USER_DISCOUNT_ADD_FAIL = 'PRICE_USER_DISCOUNT_ADD_FAIL';

export const PRICE_USER_DISCOUNT_EDIT_REQUEST = 'PRICE_USER_DISCOUNT_EDIT_REQUEST';
export const PRICE_USER_DISCOUNT_EDIT_SUCCESS = 'PRICE_USER_DISCOUNT_EDIT_SUCCESS';
export const PRICE_USER_DISCOUNT_EDIT_FAIL = 'PRICE_USER_DISCOUNT_EDIT_FAIL';

export const PRICE_USER_DISCOUNT_DELETE_REQUEST = 'PRICE_USER_DISCOUNT_DELETE_REQUEST';
export const PRICE_USER_DISCOUNT_DELETE_SUCCESS = 'PRICE_USER_DISCOUNT_DELETE_SUCCESS';
export const PRICE_USER_DISCOUNT_DELETE_FAIL = 'PRICE_USER_DISCOUNT_DELETE_FAIL';