export const PRODUCT_CAROUSEL_CREATE_REQUEST = 'PRODUCT_CAROUSEL_CREATE_REQUEST';
export const PRODUCT_CAROUSEL_CREATE_SUCCESS = 'PRODUCT_CAROUSEL_CREATE_SUCCESS';
export const PRODUCT_CAROUSEL_CREATE_FAIL = 'PRODUCT_CAROUSEL_CREATE_FAIL';

export const PRODUCT_CAROUSEL_LIST_REQUEST = 'PRODUCT_CAROUSEL_LIST_REQUEST';
export const PRODUCT_CAROUSEL_LIST_SUCCESS = 'PRODUCT_CAROUSEL_LIST_SUCCESS';
export const PRODUCT_CAROUSEL_LIST_FAIL = 'PRODUCT_CAROUSEL_LIST_FAIL';

export const PRODUCT_CAROUSEL_EDIT_REQUEST = 'PRODUCT_CAROUSEL_EDIT_REQUEST';
export const PRODUCT_CAROUSEL_EDIT_SUCCESS = 'PRODUCT_CAROUSEL_EDIT_SUCCESS';
export const PRODUCT_CAROUSEL_EDIT_FAIL = 'PRODUCT_CAROUSEL_EDIT_FAIL';

export const PRODUCT_CAROUSEL_DELETE_REQUEST = 'PRODUCT_CAROUSEL_DELETE_REQUEST';
export const PRODUCT_CAROUSEL_DELETE_SUCCESS = 'PRODUCT_CAROUSEL_DELETE_SUCCESS';
export const PRODUCT_CAROUSEL_DELETE_FAIL = 'PRODUCT_CAROUSEL_DELETE_FAIL';