export const PRODUCT_CATEGORY_CREATE_REQUEST = 'PRODUCT_CATEGORY_CREATE_REQUEST';
export const PRODUCT_CATEGORY_CREATE_SUCCESS = 'PRODUCT_CATEGORY_CREATE_SUCCESS';
export const PRODUCT_CATEGORY_CREATE_FAIL = 'PRODUCT_CATEGORY_CREATE_FAIL';

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

export const PRODUCT_POPULAR_CATEGORY_LIST_REQUEST = 'PRODUCT_POPULAR_CATEGORY_LIST_REQUEST';
export const PRODUCT_POPULAR_CATEGORY_LIST_SUCCESS = 'PRODUCT_POPULAR_CATEGORY_LIST_SUCCESS';
export const PRODUCT_POPULAR_CATEGORY_LIST_FAIL = 'PRODUCT_POPULAR_CATEGORY_LIST_FAIL';

export const PRODUCT_CATEGORY_EDIT_REQUEST = 'PRODUCT_CATEGORY_EDIT_REQUEST';
export const PRODUCT_CATEGORY_EDIT_SUCCESS = 'PRODUCT_CATEGORY_EDIT_SUCCESS';
export const PRODUCT_CATEGORY_EDIT_FAIL = 'PRODUCT_CATEGORY_EDIT_FAIL';

export const PRODUCT_CATEGORY_DELETE_REQUEST = 'PRODUCT_CATEGORY_DELETE_REQUEST';
export const PRODUCT_CATEGORY_DELETE_SUCCESS = 'PRODUCT_CATEGORY_DELETE_SUCCESS';
export const PRODUCT_CATEGORY_DELETE_FAIL = 'PRODUCT_CATEGORY_DELETE_FAIL';