export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const PRODUCT_NAME_LIST_REQUEST = 'PRODUCT_NAME_LIST_REQUEST';
export const PRODUCT_NAME_LIST_SUCCESS = 'PRODUCT_NAME_LIST_SUCCESS';
export const PRODUCT_NAME_LIST_FAIL = 'PRODUCT_NAME_LIST_FAIL';

export const PRODUCT_RECOMMENDED_LIST_REQUEST = 'PRODUCT_RECOMMENDED_LIST_REQUEST';
export const PRODUCT_RECOMMENDED_LIST_SUCCESS = 'PRODUCT_RECOMMENDED_LIST_SUCCESS';
export const PRODUCT_RECOMMENDED_LIST_FAIL = 'PRODUCT_RECOMMENDED_LIST_FAIL';

export const PRODUCT_OUT_OF_STOCK_REQUEST = 'PRODUCT_OUT_OF_STOCK_REQUEST';
export const PRODUCT_OUT_OF_STOCK_SUCCESS = 'PRODUCT_OUT_OF_STOCK_SUCCESS';
export const PRODUCT_OUT_OF_STOCK_FAIL = 'PRODUCT_OUT_OF_STOCK_FAIL';

export const PRODUCT_CALL_CENTER_NAME_LIST_REQUEST = 'PRODUCT_CALL_CENTER_NAME_LIST_REQUEST';
export const PRODUCT_CALL_CENTER_NAME_LIST_SUCCESS = 'PRODUCT_CALL_CENTER_NAME_LIST_SUCCESS';
export const PRODUCT_CALL_CENTER_NAME_LIST_FAIL = 'PRODUCT_CALL_CENTER_NAME_LIST_FAIL';

export const PRODUCT_UPLOAD_NAME_LIST_REQUEST = 'PRODUCT_UPLOAD_NAME_LIST_REQUEST';
export const PRODUCT_UPLOAD_NAME_LIST_SUCCESS = 'PRODUCT_UPLOAD_NAME_LIST_SUCCESS';
export const PRODUCT_UPLOAD_NAME_LIST_FAIL = 'PRODUCT_UPLOAD_NAME_LIST_FAIL';