export const PRODUCT_REVIEW_SAVE_REQUEST = 'PRODUCT_REVIEW_SAVE_REQUEST';
export const PRODUCT_REVIEW_SAVE_SUCCESS = 'PRODUCT_REVIEW_SAVE_SUCCESS';
export const PRODUCT_REVIEW_SAVE_FAIL = 'PRODUCT_REVIEW_SAVE_FAIL';

export const PRODUCT_REVIEW_LIST_REQUEST = 'PRODUCT_REVIEW_LIST_REQUEST';
export const PRODUCT_REVIEW_LIST_SUCCESS = 'PRODUCT_REVIEW_LIST_SUCCESS';
export const PRODUCT_REVIEW_LIST_FAIL = 'PRODUCT_REVIEW_LIST_FAIL';

export const PRODUCT_REVIEW_EDIT_REQUEST = 'PRODUCT_REVIEW_EDIT_REQUEST';
export const PRODUCT_REVIEW_EDIT_SUCCESS = 'PRODUCT_REVIEW_EDIT_SUCCESS';
export const PRODUCT_REVIEW_EDIT_FAIL = 'PRODUCT_REVIEW_EDIT_FAIL';

export const PRODUCT_REVIEW_DELETE_REQUEST = 'PRODUCT_REVIEW_DELETE_REQUEST';
export const PRODUCT_REVIEW_DELETE_SUCCESS = 'PRODUCT_REVIEW_DELETE_SUCCESS';
export const PRODUCT_REVIEW_DELETE_FAIL = 'PRODUCT_REVIEW_DELETE_FAIL';

export const MY_REVIEW_LIST_REQUEST = 'MY_REVIEW_LIST_REQUEST';
export const MY_REVIEW_LIST_SUCCESS = 'MY_REVIEW_LIST_SUCCESS';
export const MY_REVIEW_LIST_FAIL = 'MY_REVIEW_LIST_FAIL';

export const USER_REVIEW_LIST_REQUEST = 'USER_REVIEW_LIST_REQUEST';
export const USER_REVIEW_LIST_SUCCESS = 'USER_REVIEW_LIST_SUCCESS';
export const USER_REVIEW_LIST_FAIL = 'USER_REVIEW_LIST_FAIL';