export const SUGGEST_PRODUCT_CREATE_REQUEST = 'SUGGEST_PRODUCT_CREATE_REQUEST';
export const SUGGEST_PRODUCT_CREATE_SUCCESS = 'SUGGEST_PRODUCT_CREATE_SUCCESS';
export const SUGGEST_PRODUCT_CREATE_FAIL = 'SUGGEST_PRODUCT_CREATE_FAIL';

export const SUGGEST_PRODUCT_LIST_REQUEST = 'SUGGEST_PRODUCT_LIST_REQUEST';
export const SUGGEST_PRODUCT_LIST_SUCCESS = 'SUGGEST_PRODUCT_LIST_SUCCESS';
export const SUGGEST_PRODUCT_LIST_FAIL = 'SUGGEST_PRODUCT_LIST_FAIL';

export const SUGGEST_PRODUCT_DELETE_REQUEST = 'SUGGEST_PRODUCT_DELETE_REQUEST';
export const SUGGEST_PRODUCT_DELETE_SUCCESS = 'SUGGEST_PRODUCT_DELETE_SUCCESS';
export const SUGGEST_PRODUCT_DELETE_FAIL = 'SUGGEST_PRODUCT_DELETE_FAIL';