export const VIDEOS_CREATE_REQUEST = 'VIDEOS_CREATE_REQUEST';
export const VIDEOS_CREATE_SUCCESS = 'VIDEOS_CREATE_SUCCESS';
export const VIDEOS_CREATE_FAIL = 'VIDEOS_CREATE_FAIL';

export const VIDEOS_LIST_REQUEST = 'VIDEOS_LIST_REQUEST';
export const VIDEOS_LIST_SUCCESS = 'VIDEOS_LIST_SUCCESS';
export const VIDEOS_LIST_FAIL = 'VIDEOS_LIST_FAIL';

export const VIDEOS_EMPLOYEE_LIST_REQUEST = 'VIDEOS_EMPLOYEE_LIST_REQUEST';
export const VIDEOS_EMPLOYEE_LIST_SUCCESS = 'VIDEOS_EMPLOYEE_LIST_SUCCESS';
export const VIDEOS_EMPLOYEE_LIST_FAIL = 'VIDEOS_EMPLOYEE_LIST_FAIL';

export const VIDEOS_EDIT_REQUEST = 'VIDEOS_EDIT_REQUEST';
export const VIDEOS_EDIT_SUCCESS = 'VIDEOS_EDIT_SUCCESS';
export const VIDEOS_EDIT_FAIL = 'VIDEOS_EDIT_FAIL';

export const VIDEOS_COOKING_VIDEOS_CONTENT_ADD_REQUEST = 'VIDEOS_COOKING_VIDEOS_CONTENT_ADD_REQUEST';
export const VIDEOS_COOKING_VIDEOS_CONTENT_ADD_SUCCESS = 'VIDEOS_COOKING_VIDEOS_CONTENT_ADD_SUCCESS';
export const VIDEOS_COOKING_VIDEOS_CONTENT_ADD_FAIL = 'VIDEOS_COOKING_VIDEOS_CONTENT_ADD_FAIL';

export const VIDEOS_COOKING_VIDEOS_CONTENT_EDIT_REQUEST = 'VIDEOS_COOKING_VIDEOS_CONTENT_EDIT_REQUEST';
export const VIDEOS_COOKING_VIDEOS_CONTENT_EDIT_SUCCESS = 'VIDEOS_COOKING_VIDEOS_CONTENT_EDIT_SUCCESS';
export const VIDEOS_COOKING_VIDEOS_CONTENT_EDIT_FAIL = 'VIDEOS_COOKING_VIDEOS_CONTENT_EDIT_FAIL';

export const VIDEOS_COOKING_VIDEOS_CONTENT_DELETE_REQUEST = 'VIDEOS_COOKING_VIDEOS_CONTENT_DELETE_REQUEST';
export const VIDEOS_COOKING_VIDEOS_CONTENT_DELETE_SUCCESS = 'VIDEOS_COOKING_VIDEOS_CONTENT_DELETE_SUCCESS';
export const VIDEOS_COOKING_VIDEOS_CONTENT_DELETE_FAIL = 'VIDEOS_COOKING_VIDEOS_CONTENT_DELETE_FAIL';

export const VIDEOS_KITCHEN_HACKS_CONTENT_ADD_REQUEST = 'VIDEOS_KITCHEN_HACKS_CONTENT_ADD_REQUEST';
export const VIDEOS_KITCHEN_HACKS_CONTENT_ADD_SUCCESS = 'VIDEOS_KITCHEN_HACKS_CONTENT_ADD_SUCCESS';
export const VIDEOS_KITCHEN_HACKS_CONTENT_ADD_FAIL = 'VIDEOS_KITCHEN_HACKS_CONTENT_ADD_FAIL';

export const VIDEOS_KITCHEN_HACKS_CONTENT_EDIT_REQUEST = 'VIDEOS_KITCHEN_HACKS_CONTENT_EDIT_REQUEST';
export const VIDEOS_KITCHEN_HACKS_CONTENT_EDIT_SUCCESS = 'VIDEOS_KITCHEN_HACKS_CONTENT_EDIT_SUCCESS';
export const VIDEOS_KITCHEN_HACKS_CONTENT_EDIT_FAIL = 'VIDEOS_KITCHEN_HACKS_CONTENT_EDIT_FAIL';

export const VIDEOS_KITCHEN_HACKS_CONTENT_DELETE_REQUEST = 'VIDEOS_KITCHEN_HACKS_CONTENT_DELETE_REQUEST';
export const VIDEOS_KITCHEN_HACKS_CONTENT_DELETE_SUCCESS = 'VIDEOS_KITCHEN_HACKS_CONTENT_DELETE_SUCCESS';
export const VIDEOS_KITCHEN_HACKS_CONTENT_DELETE_FAIL = 'VIDEOS_KITCHEN_HACKS_CONTENT_DELETE_FAIL';

export const VIDEOS_HEALTH_TIPS_CONTENT_ADD_REQUEST = 'VIDEOS_HEALTH_TIPS_CONTENT_ADD_REQUEST';
export const VIDEOS_HEALTH_TIPS_CONTENT_ADD_SUCCESS = 'VIDEOS_HEALTH_TIPS_CONTENT_ADD_SUCCESS';
export const VIDEOS_HEALTH_TIPS_CONTENT_ADD_FAIL = 'VIDEOS_HEALTH_TIPS_CONTENT_ADD_FAIL';

export const VIDEOS_HEALTH_TIPS_CONTENT_EDIT_REQUEST = 'VIDEOS_HEALTH_TIPS_CONTENT_EDIT_REQUEST';
export const VIDEOS_HEALTH_TIPS_CONTENT_EDIT_SUCCESS = 'VIDEOS_HEALTH_TIPS_CONTENT_EDIT_SUCCESS';
export const VIDEOS_HEALTH_TIPS_CONTENT_EDIT_FAIL = 'VIDEOS_HEALTH_TIPS_CONTENT_EDIT_FAIL';

export const VIDEOS_HEALTH_TIPS_CONTENT_DELETE_REQUEST = 'VIDEOS_HEALTH_TIPS_CONTENT_DELETE_REQUEST';
export const VIDEOS_HEALTH_TIPS_CONTENT_DELETE_SUCCESS = 'VIDEOS_HEALTH_TIPS_CONTENT_DELETE_SUCCESS';
export const VIDEOS_HEALTH_TIPS_CONTENT_DELETE_FAIL = 'VIDEOS_HEALTH_TIPS_CONTENT_DELETE_FAIL';